title: Default Page

columns:
  main:
    width: 2/3
    sections:
      pages:
        template: page
  sidebar:
    width: 1/3
    fields:
      sections:
        fields:
          type: fields
          fields:
            text:
              label: Text
              type: writer



