<p>
  The HTML for this page is generated by
  the template <a href="https://github.com/getkirby/demokit/tree/main/site/templates/<?= $page->template()->name() ?>.php"><?= $page->template()->name() ?>.php</a>.
</p>
<p>
  All templates can be found in the <a href="https://github.com/getkirby/demokit/tree/main/site/templates">/site/templates</a> folder.
</p>
<p>
  To learn more about Kirby’s templates, please check out our docs:
  <a href="https://getkirby.com/docs">https://getkirby.com/docs</a>
</p>
