<?php snippet([$example . '/header', 'header']) ?>
<?= css('assets/prism/prism.css') ?>

<header class="intro">
  <h1 class="h1">
    <small><a href="<?= $page->url() ?>"><?= $page->title() ?></a></small><br>
    Template
  </h1>
</header>

<div class="grid">
  <div class="column text" style="--columns: 3">
    <p>
      The HTML for this page is generated by
      the template <a href="https://github.com/getkirby/demokit/tree/master/site/templates/<?= $page->template()->name() ?>.php"><?= $page->template()->name() ?>.php</a>
    <p>
    <p>
      All templates can be found in the <a href="https://github.com/getkirby/demokit/tree/master/site/templates">/site/templates</a> folder
    </p>
    <p>
      To learn more about Kirby's templates, please check out our docs:
      <a href="https://getkirby.com/docs">https://getkirby.com/docs</a>
    <p>
  </div>
  <div class="column text" style="--columns: 9">
    <pre><code class="language-php"><?= htmlspecialchars(F::read($page->template()->file())) ?></code></pre>
  </div>
</div>

<?= js('assets/prism/prism.js') ?>

<?php snippet([$example . '/footer', 'footer']) ?>
